# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       tzdata-timed

# >> macros
# << macros

Summary:    Data files for the time daemon, timed
Version:    2013b
Release:    1
Group:      System/System Control
License:    Public Domain
BuildArch:  noarch
URL:        https://github.com/nemomobile/tzdata-timed
Source0:    %{name}-%{version}.tar.bz2
Source100:  tzdata-timed.yaml
Requires:   tzdata

%description
Timed daemon datafiles that combine information about time zones,
and mobile country codes.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/tzdata-timed
# << files
